version: '3.8'

services:
  postgres_db:
    image: postgres:15 # Or your preferred PostgreSQL version
    container_name: insightlens_postgres_db
    environment:
      POSTGRES_USER: insightlens_user # Matches application.properties
      POSTGRES_PASSWORD: insightlens   # Matches application.properties
      POSTGRES_DB: insightlens_db     # Matches application.properties
    ports:
      - "5433:5432" # Exposes PostgreSQL on host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - insightlens_network

  insightlens-embedding-service-python:
    container_name: insightlens_embedding_python
    build:
      context: ./insightlens-embedding-service-python
      dockerfile: Dockerfile # Assumes Dockerfile is in the root of this service
    ports:
      - "8000:8000" # Exposes FastAPI app on host port 8000 (internal container port should also be 8000)
    # The command to run uvicorn should be in your Dockerfile's CMD or ENTRYPOINT
    # e.g., CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      # For development with hot-reloading for Python/FastAPI:
      - ./insightlens-embedding-service-python/app:/app/app
    networks:
      - insightlens_network

  insightlens-llm-analysis-service-python:
    container_name: insightlens_llm_python
    build:
      context: ./insightlens-llm-analysis-service-python
      dockerfile: Dockerfile # Assumes Dockerfile is in the root of this service
    ports:
      - "8001:8001" # Exposes FastAPI app on host port 8001 (internal container port should also be 8001)
    # Command to run uvicorn should be in your Dockerfile
    # e.g., CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    volumes:
      # For development with hot-reloading:
      - ./insightlens-llm-analysis-service-python/app:/app/app
    networks:
      - insightlens_network

  # insightlens-frontend-react:
  #   container_name: insightlens_frontend_react
  #   build:
  #     context: ./insightlens-frontend-react
  #     dockerfile: Dockerfile # Assumes Dockerfile is in the root of this service
  #   ports:
  #     - "3000:3000" # Exposes React dev server (or your app) on host port 3000
  #   volumes:
  #     # For development with hot-reloading for React:
  #     - ./insightlens-frontend-react/src:/app/src
  #     - ./insightlens-frontend-react/public:/app/public
  #   environment:
  #     - NODE_ENV=development # Or as needed by your React setup
  #     # Ensure your React app's API calls point to http://localhost:8080 (or the backend's exposed host port)
  #     # Or configure a proxy in React's package.json
  #   networks:
  #     - insightlens_network

volumes:
  postgres_data: # Named volume for PostgreSQL data persistence

networks:
  insightlens_network:
    driver: bridge